#!/usr/bin/env bash

set -o errtrace
set -o pipefail

#---
# @stdout Help
print_help() {
	cat <<-EOF
		Run tests.

		Usage:
		  $script_name
		  $script_name -h

		Options:
		  -h  Print help.
	EOF
}

#---
# @param $1 Title of the section.
# @stdout Output that marks the start of the section.
start_section() {
	local tty_fg_blue=$'\033[34m'
	local tty_reset=$'\033[0m'

	echo
	printf "%s" "$tty_fg_blue# $1 "
	eval 'printf "#%.0s" {1..'"$((80 - ${#1} - 3))"'}'
	printf "%s\n" "$tty_reset"
	echo
}

script_name=$(basename -- "$0")
project_dir=$(cd -- "$(dirname -- "$0")/.." &>/dev/null && pwd) || exit
shells=(posh dash ksh bash)
exit_status=0

while getopts :h option; do
	case $option in
		h)
			print_help
			exit
			;;
		\?)
			echo "Option is unknown: -$OPTARG" >&2
			exit 1
			;;
	esac
done

cd -- "$project_dir" || exit

for shell in "${shells[@]}"; do
	start_section "$shell"
	prove --shuffle --ext sh --failures --comments --parse --exec "$shell" || exit_status=1
done

exit "$exit_status"
