#!/usr/bin/env bash

# The curly braces (with the final `exit`) wrapping this script ensure that the
# whole script is loaded into memory before it is executed. As a result, issues
# are prevented when this script is formatted by itself.
{
	set -o errtrace
	set -o pipefail
	shopt -s globstar || exit

	#---
	# @stdout Help
	print_help() {
		cat <<-EOF
			Format the project's files.

			Usage:
			  $script_name
			  $script_name -c
			  $script_name -h

			Options:
			  -c  Check whether files are properly formatted. If issues are detected, a
			      non-zero exit status is used. Please note that no files are formatted
			      when this option is used.
			  -h  Print help.
		EOF
	}

	script_name=$(basename -- "$0")
	project_dir=$(cd -- "$(dirname -- "$0")/.." &>/dev/null && pwd) || exit
	# shellcheck disable=SC2125
	GLOBIGNORE=$project_dir/.git/*
	shebang_regex='^#!\s?/(usr/)?bin/(env\s+)?(sh|bash)$'
	shfmt_opts=(-bn -ci)

	while getopts :ch option; do
		case $option in
			c)
				check=1
				;;
			h)
				print_help
				exit
				;;
			\?)
				echo "Option is unknown: -$OPTARG" >&2
				exit 1
				;;
		esac
	done

	paths=("$project_dir"/**/*)
	for path in "${paths[@]}"; do
		if [[ ! -r $path ]]; then
			echo "Not readable: $path" >&2
			exit 1
		elif [[ ! -f $path ]]; then
			continue # We can ignore directories that were matched by globstar.
		elif [[ $path = *.sh ]]; then
			shfmt_files+=("$path")
		elif [[ ${path##*/} != *.* ]] \
			&& read -r shebang <"$path" \
			&& [[ $shebang =~ $shebang_regex ]]; then
			if [[ ${BASH_REMATCH[3]} = bash || ${BASH_REMATCH[3]} = sh ]]; then
				shfmt_files+=("$path")
			fi
		fi
	done

	if [[ $check -eq 1 ]]; then
		shfmt_opts+=(-d)
	else
		shfmt_opts+=(-w)
	fi

	shfmt "${shfmt_opts[@]}" -- "${shfmt_files[@]}"

	exit
}
