name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  GitHub:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.0.2
      - run: >
          curl
          --fail
          --no-progress-meter
          --request POST
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          --header "Accept: application/vnd.github.v3+json"
          --data-raw '{"tag_name":"${{ github.ref_name }}","body":"Check the [changelog](CHANGELOG.md) for more details."}'
          https://api.github.com/repos/${{ github.repository }}/releases
